<?php
/**
 * Created by PhpStorm.
 * User: Akshat
 * Date: 7/4/2017
 * Time: 12:30 AM
 */
$config=[
    'summary_iknow'=>[
        [
            'field'=>'admission_no',
            'label'=>'Admission No',
            'rules'=>'required'
        ],
        [
            'field'=>'from',
            'label'=>'From',
            'rules'=>'required'
        ],
        [
            'field'=>'to',
            'label'=>'To',
            'rules'=>'required'
        ]
    ],

    'summary'=>[
        [
            'field'=>'summary_on',
            'label'=>'Summary',
            'rules'=>'required'
        ]
    ],
    'id_card'=>[
        [
            'field'=>'class',
            'label'=>'Name',
            'rules'=>'required'
        ]
    ],
    'sln'=>[
        [
            'field'=>'name',
            'label'=>'Name',
            'rules'=>'required'
        ]
    ],
    'route'=>[
        [
            'field'=>'route_name',
            'label'=>'Route Name',
            'rules'=>'required'
        ]

    ],
    'account_delete'=>[
        [
            'field'=>'account_name_delete',
            'label'=>'Account Name',
            'rules'=>'required'
        ]
    ],
    'payments'=>[
        [
            'field'=>'vch_no',
            'label'=>'Voucher Number',
            'rules'=>'required'
        ]
    ],
    'organisation_info'=>[
        [
            'field'=>'name',
            'label'=>'Organisation Name',
            'rules'=>'required'
        ]
    ],
    'fees_head_del'=>[
        [
            'field'=>'fees_heading',
            'label'=>'Fees Heading',
            'rules'=>'required'
        ]
    ],
    'fees_head'=>[
        [
            'field'=>'fees_heading',
            'label'=>'Fees Heading',
            'rules'=>'required'
        ]
    ],
    'account'=>[
        [
            'field'=>'account_name',
            'label'=>'Account Group Name',
            'rules'=>'required'
        ]
    ],
    'account_gr_delete'=>
        [
            [
                'field'=>'account_group_delete',
                'label'=>'Account Group Name',
                'rules'=>'required'
            ]
        ],
    'account_group'=>
        [
            [
                'field'=>'account_group_name',
                'label'=>'Account Group Name',
                'rules'=>'required'
            ]
        ],
    'fhg'=>
        [
            [
                'field'=>'fees_head_group_name',
                'label'=>'Fees Head Group',
                'rules'=>'required'
            ]
        ],
    'adm_form'=>
        [
            [
                'field'=>'adm_no',
                'label'=>'Admission No.',
                'rules'=>'required'
            ]
        ],
    'section_del'=>
        [
            [
                'field'=>'section_delete',
                'label'=>'Section',
                'rules'=>'required'
            ]
        ],
    'house'=>
        [
            [
                'field'=>'house_name',
                'label'=>'House Name',
                'rules'=>'required'
            ]
        ],
    'section'=>
        [
            [
                'field'=>'section_name',
                'label'=>'Section',
                'rules'=>'required'
            ]
        ],
    'caste'=>
        [
            [
                'field'=>'caste_name',
                'label'=>'Caste Name',
                'rules'=>'required'
            ]
        ],
    'category'=>
        [
            [
                'field'=>'category_name',
                'label'=>'Category Name',
                'rules'=>'required'
            ]
        ],

    'admin_form' =>
        [
            [
                'field'=>'email',
                'label'=>'Email',
                'rules'=>'required'
            ],
            [
                'field'=>'password',
                'label'=>'Password',
                'rules'=>'required'
            ]
        ],
    'student'=>
        [
            [
                'field'=>'student_first_name',
                'label'=>'Student First Name',
                'rules'=>'required'

            ],
            [
                'field'=>'admission_no',
                'label'=>'Admission Number',
                'rules'=>'required'
            ]
        ],
    'address'=>
        [
            [
                'field'=>'house_no',
                'label'=>'House Number',
                'rules'=>'required'
            ],
            [
                'field'=>'city',
                'label'=>'City',
                'rules'=>'required'
            ],
        ],
    'misc_stu_details'=>
        [
            [
                'field'=>'las',
                'label'=>'Last attended School',
                'rules'=>'required'
            ]
        ],
    'attach'=>
        [
            [
                'field'=>'admission_form_no',
                'label'=>'Admission form number',
                'rules'=>'required'
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ]
        ],
    'contact_us'=>
        [
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ]
        ],
    'misc_info'=>
        [
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
        ],
    'balance'=>
        [
            [
                'field'=>'ledger_balance',
                'label'=>'Ledger Balance',
                'rules'=>'required'
            ],
        ],
    'other_info'=>
        [
            [
                'field'=>'fathers_first_name',
                'label'=>'Fathers First Name',
                'rules'=>'required'
            ],
            [
                'field'=>'mothers_first_name',
                'label'=>'Mothers First Name',
                'rules'=>'required'
            ]

        ],
    'owner'=>
        [
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ]
        ],
    'class'=>
        [
            [
                'field'=>'class',
                'label'=>'Class',
                'rules'=>'required'
            ]

        ],
    'class_del'=>
        [
            [
            'field'=>'class_delete',
            'label'=>'Class',
            'rules'=>'required'
            ]
        ],
    'category_del'=>
        [
            [
                'field'=>'category_delete',
                'label'=>'Category Name',
                'rules'=>'required'
            ]
        ],
    'house_del'=>
        [
            [
                'field'=>'house_delete',
                'label'=>'House Name',
                'rules'=>'required'
            ]
        ],
    'family_del'=>
        [
            [
                'field'=>'family_delete',
                'label'=>'Family Name',
                'rules'=>'required'
            ]
        ],
    'family'=>
        [
            [
                'field'=>'family_name',
                'label'=>'Family Name',
                'rules'=>'required'
            ]
        ],
    'sort_admission'=>[
        [
            'field'=>'sort_col_1',
            'label'=>'This',
            'rules'=>'required'
        ]
    ],
    'search_admission'=>[
        [
            'field'=>'search_col_1',
            'label'=>'This',
            'rules'=>'required'
        ]
    ],
    'fees_head_group_del'=>[
        [
            'field'=>'fees_head_group_name_del',
            'label'=>'Fees Head Group',
            'rules'=>'required'
        ]
    ],
    'fees_plan_category'=>[
        [
            'field'=>'category_name',
            'label'=>'Category',
            'rules'=>'required'
        ]
    ],
    'fees_plan_category_del'=>[
        [
            'field'=>'category_delete',
            'label'=>'Category',
            'rules'=>'required'
        ]
    ],
    'fees_receipt_search'=>[
        [
            'field'=>'admission_no',
            'label'=>'Admission No.',
            'rules'=>'required'
        ]
    ],
    'attend_new'=>[
        [
            'field'=>'class',
            'label'=>'Class',
            'rules'=>'required'
        ]
    ],
    'gatepass'=>[
        [
            'field'=>'name',
            'label'=>'Name',
            'rules'=>'required'
        ]
    ],
    [
        'subject'=>
        [
            'field'=>'subject_name',
            'label'=>'Subject',
            'rules'=>'required'
        ]
    ]

];