<?php
/**
 * Created by PhpStorm.
 * User: Akshat
 * Date: 7/4/2017
 * Time: 12:30 AM
 */
$config=[

    'admin_form' =>
        [
            [
                'field'=>'email',
                'label'=>'Email',
                'rules'=>'required'
            ],
            [
                'field'=>'password',
                'label'=>'Password',
                'rules'=>'required'
            ]
        ],
    'student'=>
        [
            [
                'field'=>'student_first_name',
                'label'=>'Student First Name',
                'rules'=>'required'

            ],
            [
                'field'=>'student_last_name',
                'label'=>'Student Last Name',
                'rules'=>'required'
            ],
            [
                'field'=>'admission_no',
                'label'=>'Admission Number',
                'rules'=>'required'
            ],
            [
            'field'=>'student_dob',
            'label'=>'Date Of Birth',
            'rules'=>'required'
            ],
            [
                'field'=>'student_roll_no',
                'label'=>'Roll Number',
                'rules'=>'required'
            ]
        ],
    'address'=>
        [
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ]
        ],
    'attachements'=>
        [
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ]
        ],
    'contact_us'=>
        [
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ]
        ],
    'misc_info'=>
        [
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
        ],
    'old_balance'=>
        [
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ]
        ],
    'other_info'=>
        [
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ]
        ],
    'owner'=>
        [
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ],
            [
                'field'=>'',
                'label'=>'',
                'rules'=>''
            ]
        ]
];